[package]
name = "logging_memory_region_client"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.101"
solana-client = "3.1.8"
solana-sdk = "3.0.0"
solana-transaction-status = "3.1.8"
