[package]
name = "my_macro"
version = "0.1.0"
edition = "2024"


[lib]
proc-macro = true


[dependencies]
syn = "2"         # → parse Rust code
quote = "1"       # → generate Rust code
proc-macro2 = "1" # → compiler interface
